doctrine:
  dbal:
    # configure these for your database server
    default_connection: default
    connections:
      default:
        driver: 'pdo_mysql'
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '%env(DATABASE_SERVER_VERSION)%'
        charset: utf8mb4
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
        mapping_types:
          enum: string
          set: string
          varbinary: string
          tinyblob: text
  orm:
    auto_generate_proxy_classes: true
    entity_managers:
      default:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        connection: default
        metadata_cache_driver:
          type: pool
          pool: doctrine_cache_adapter
        query_cache_driver:
          type: pool
          pool: doctrine_cache_adapter
        result_cache_driver:
          type: pool
          pool: doctrine_cache_adapter
        dql:
          datetime_functions:
            date: DoctrineExtensions\Query\Mysql\Date
            day: DoctrineExtensions\Query\Mysql\Day
            month: DoctrineExtensions\Query\Mysql\Month
            year: DoctrineExtensions\Query\Mysql\Year
          numeric_functions:
            Rand: DoctrineExtensions\Query\Mysql\Rand
        mappings:
          App:
            is_bundle: false
            type: annotation
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: App
          gedmo_loggable:
            type: annotation
            prefix: Gedmo\Loggable\Entity
            dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
            alias: GedmoLoggable
            is_bundle: false
