mobile_detect:
  redirect:
    full:
      is_enabled: true            # default false
      #      host: http://site.com       # with scheme (http|https), default null, url validate
      status_code: 301            # default 302
      action: no_redirect            # redirect, no_redirect, redirect_without_path
    mobile:
      is_enabled: true            # default false
      #      host: http://m.site.com     # with scheme (http|https), default null, url validate
      status_code: 301            # default 302
      action: no_redirect            # redirect, no_redirect, redirect_without_path
    tablet: ~
  service:
    mobile_detector: mobile_detect.mobile_detector.default
  cookie_expire_datetime_modifier: "+1 month"   # default
  cookie_key: "device_view"                     # default
  switch_param: "device_view"                   # default
  device_view_class: ComponentBundle\Helper\DeviceView
  request_response_listener_class: SunCat\MobileDetectBundle\EventListener\RequestResponseListener
  twig_extension_class: SunCat\MobileDetectBundle\Twig\Extension\MobileDetectExtension
