vich_uploader:
  db_driver: orm
  mappings:
    images:
      uri_prefix: 'uploads/images'
      upload_destination: '%kernel.project_dir%/public/uploads/images'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      directory_namer: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    files:
      uri_prefix: 'uploads/files'
      upload_destination: '%kernel.project_dir%/public/uploads/files'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      directory_namer: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
